#!/bin/bash

source config.sh
echo $token_key
echo ${token_key}
#curl -X POST --data-ascii '{"function":"ecopadq.tasks.datatask.teco_spruce_pulldata","queue":"celery","args":[],"kwargs":{  },"tags": []}' http://0.0.0.0:8888/api/queue/run/ecopadq.tasks.datatask.teco_spruce_pulldata/.json -H Content-Type:application/json -H 'Authorization: Token ${token_key}'
